---

# Basic user creation
- name: Create IAM users with API keys
  iam:
    iam_type: user
    name: "{{ user_email }}"
    state: present
    password: "{{ aws_iam_pass }}"
    #access_key_state: create
    groups: CloudAdminEngineer
    update_password: on_create
  ignore_errors: True
  failed_when: False
  tags:
  - create_users
