---

- include: provision.yml


#- include: ip_rules.yml
#  when: mach_state is defined and mach_state == "present"

#- include: ssh.yml
#  when: mach_state is defined and mach_state == "present"

- name: bla bla
  action: ec2_facts
  action: debug msg="{{ ansible_ec2_instance_type }}"
  tags: ec2_facts

- name: bla 2
  action: debug msg="{{ ansible_ec2_instance_type }}"