---

- name: provision | Provision a set of instances
  ec2:
     group: "{{ aws_group | default(omit) }}"
     group_id: "{{ aws_group_id | default(omit) }}"
     instance_type: "{{ aws_instance_type }}"
     image: "{{ aws_image }}"
     region: "{{ aws_region }}"
     wait: "{{ aws_wait | default(omit) }}"
     exact_count: "{{ aws_exact_count | default(omit) }}"
     count_tag: "{{ aws_count_tag |default(omit) }}"
     keypair: "{{ aws_keypair }}"
     instance_tags: "{{ aws_instance_tags | default(omit)}}"
  register: ec2