---
# - name: provision | Print aws_user_data varaible
#  debug: var=aws_user_data

- name: provision | Provision a set of instances
  ec2:
     group: "{{ aws_group | default(omit) }}"
     group_id: "{{ aws_group_id | default(omit) }}"
     instance_type: "{{ aws_instance_type }}"
     image: "{{ aws_image }}"
     region: "{{ aws_region }}"
     wait: "{{ aws_wait | default(omit) }}"
     exact_count: "{{ aws_exact_count | default(omit) }}"
     count_tag: "{{ aws_count_tag | default(omit) }}"
     keypair: "{{ aws_keypair }}"
     user_data: "{{ aws_user_data | default(omit) }} "
     instance_tags: "{{ aws_instance_tags | default(omit)}}"
  register: ec2

#- name: provision | Waiting for winrm port to open
#  wait_for:
#    port="{{ ansible_ssh_port | default('22') }}"
#    host="{{ ec2.tagged_instances.public_ip }}"
#    delay=1
#    timeout=5
#  search_regex=OpenSSH
- name: provision | Mail confimration module
  local_action: mail
                host='smtp.strato.de'
                port=465
                username='info@web-wand.de'
                password='Fre!s!ng2015'
                headers="Content-type=text/html"
                from="mohamed.ghaleb@amazonaws.com (Mohamed Ghaleb)"
                to="Mohamed Ghaleb <mohamed.ghaleb@gmail.com>, Mohamed Ghaleb <mohamed.ghaleb@siemens.com>"
                subject='Ansible-report'
                body='{{ lookup("file", "../../windows_install/files/jump_users_mail.txt") }}'
  tags:
    - e_mail