---
aws_instances_name  : "{{ inventory_hostname }}"
tag_group           : "jump"
aws_group           : "ghaleb_win"
aws_instance_type   : "t2.micro"
aws_image           : "ami-c887bed5"  # Windows_Server-2012-RTM-English-64Bit-Base-2015.06.10 
aws_wait            : "true"
aws_exact_count     : "1" # The number of computers to provision
aws_count_tag       :
       Name         : "{{ aws_instances_name }}"
       Group        : "{{ tag_group }} "

aws_instance_tags   :
       Name         : "{{ aws_instances_name }}"
       Group        : "{{ tag_group }} "
aws_keypair         : "ghaleb2"

# Default variable winrm port and windows user
ansible_ssh_port    : 5986  
ansible_ssh_user    : Administrator 

aws_user_data       : |
                        <powershell>
                        echo "Trying to set policy " > C:\bootscript.txt
                        Set-ExecutionPolicy RemoteSigned
                        echo "Downloading  ConfigureRemotingForAnsible.ps1" >> C:\bootscript.txt
                        $file = "C:\ConfigureRemotingForAnsible.ps1"
                        $webclient = New-Object System.Net.WebClient
                        $url = "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
                        $webclient.DownloadFile($url,$file)
                        echo "Invoke-Expression  ConfigureRemotingForAnsible.ps1" >> C:\bootscript.txt
                        Invoke-Expression C:\ConfigureRemotingForAnsible.ps1
                        echo "Trying to change password for Admin" >> C:\bootscript.txt
                        net user Administrator {{ ansible_ssh_pass }}
                        echo "Bootstrap finished" >> C:\bootscript.txt
                        </powershell>