---

windows_install_download_directory : 'C:\Users\{{ windows_install_user }}\Downloads'

windows_install_msi                :
                                     - url: 'http://web-wand.de/Thinfinity_Remote_Desktop_Workstation_Setup_x64.msi'
                                       dest: 'C:\\Users\\{{ windows_install_user }}\\Downloads\\Thinfinity_Remote_Desktop_Workstation_Setup_x64.msi'

windows_install_exe                : 
                                     - url: 'http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe'
                                       dest: 'C:\\Users\\{{ windows_install_user }}\\Desktop\\putty.exe'

windows_install_copy_thinRDP       :
                                     - src: 'Thinfinity.RemoteDesktop.Workstation.ini'
                                       dest: 'C:\ProgramData\Cybele Software\Thinfinity\Remote Desktop Workstation\Thinfinity.RemoteDesktop.Workstation.ini'

windows_install_create_shortcuts   :
                                     - src: 'c:\windows\system32\mstsc.exe'
                                       dest: 'c:\Users\{{ windows_install_user }}\Desktop\Remote_Desktop.lnk'

                                     - src: 'c:\windows\system32\cmd.exe'
                                       dest: 'c:\Users\{{ windows_install_user }}\Desktop\cmd.lnk'
