---
aws_instances_name  : "{{ inventory_hostname }}"
tag_group           : "jump"
aws_group           : "ghaleb_win"
aws_instance_type   : "t2.micro"
aws_image           : "ami-c887bed5"  # Windows_Server-2012-RTM-English-64Bit-Base-2015.06.10 
aws_wait            : "true"
aws_exact_count     : "1" # The number of computers to provision
aws_count_tag       :
       Name         : "{{ aws_instances_name }}"
       Group        : "{{ tag_group }} "

aws_instance_tags   :
       Name         : "{{ aws_instances_name }}"
       Group        : "{{ tag_group }} "
aws_keypair         : "ghaleb2"

# Default variable winrm port and windows user
ansible_ssh_port    : 5986  
ansible_ssh_user    : Administrator 

aws_user_data       : |
                        sudo apt-add-repository -y ppa:ansible/ansible
                        sudo apt-get update && sudo apt-get install ansible
                        sudo apt-get install python-pip pip install -U boto
                        sudo pip install pywinrm
                        sudo apt-get remove -y vim-tiny
                        sudo apt-get install -y vim
                        sudo apt-get install -y git
                        cd /home/ubuntu/
                        mkdir git
                        cd git
                        git clone https://github.com/msghaleb/msg-ansible.git
                        cp /msg-ansible/modules/iam.py /usr/share/ansible/iam.py