---

- hosts: jump
  connection: local # Local means it will run from the management server and won't connect to run remotly (smart("ssh), local, winrm, ...)
  gather_facts: False
  roles:
    - users_creation
    - aws_provisioner

- hosts: jump
  gather_facts: False
  connection: winrm
  roles:
    - windows_install