---

#- name: fail
#  connection: local
#  debug:
#    msg="password={{ ansible_ssh_pass }}"

- name: Download file exe files
  win_get_url:
    url="{{ item.url }}"
    dest="{{ item.dest }}"
  with_items: windows_install_exe
  when: windows_install_exe is defined 
  tags:
    - download_exe

- name: Download file msi files
  win_get_url:
    url="{{ item.url }}"
    dest="{{ item.dest }}"
  with_items: windows_install_msi
  when: windows_install_msi is defined 

- name: Install msi files
  win_msi: 
    path="{{ item.dest }}"
  with_items: windows_install_msi
  when: windows_install_msi is defined 

- name: Creating Shortcuts
  win_file_lnk:
    src="{{ item.src }}"
    dest="{{ item.dest }}"
  with_items: windows_install_create_shortcuts
  when: windows_install_create_shortcuts
  tags:
    - create_shortcuts

- name: Copy ThinRDP config file
  win_copy:
    src="{{ item.src }}"
    dest="{{ item.dest }}"
  with_items: windows_install_copy_thinRDP
  when: windows_install_copy_thinRDP
  notify:
    - restart thinRDP
    - mail confimration module
  tags:
    - copy_thinrdp

