---

#- name: Creat Download directory
#  win_file: 
#    path="{{ windows_install_download_directory }}"
#    state=directory


- name: Download file exe files
  win_get_url:
    url: "{{ item.url }}" # item.url is the url of the item below in this case windows_install_exe
    dest: "{{ item.dest }}" # item.dest is the dest of the item below in this case windows_install_exe
  with_items: windows_install_exe
  when: windows_install_exe is defined 

- name: Download file msi files
  win_get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}" # item.dest is the dest of the item below in this case windows_install_msi
  with_items: windows_install_msi
  when: windows_install_msi is defined 

- name: Install msi files
  win_msi: 
    path="{{ item.dest }}" # item.dest is the dest of the item below in this case windows_install_msi
  with_items: windows_install_msi
  when: windows_install_msi is defined 

- name: Mail confimration module
  local_action: mail
                host='smtp.strato.de'
                port=465
                username='info@web-wand.de'
                password='Fre!s!ng2015'
                headers="Content-type=text/html"
                charset='UTF-8'
                from="no_reply@amazonaws.com (Mohamed Ghaleb)"
                to='{{ aws_username }}'
                subject='Your CloudFirst Sandbox access details'
                body='Dear {{ user_fname }}, {{ new_line }}{{ new_line }}Your Amazon Cloud login has been created and ready to use, below are the needed details{{ a_colon }}{{ new_line }}{{ new_line }}The url is "https{{ a_colon }}//693860272213.signin.aws.amazon.com/console"{{ new_line }}Username{{ a_colon }} {{ aws_username }}{{ new_line }}Password{{ a_colon }} {{ ansible_ssh_pass }}{{ new_line }}{{ new_line }}Your cloud system {{ inventory_hostname }} has been successfully provisioned and ready for use.{{ new_line }}{{ new_line }}Please access it using the following link https{{ a_colon }}//{{ansible_ssh_host}}{{ new_line }}{{ new_line }}Username{{ a_colon }} {{ jump_pc_username }}{{ new_line }}Password{{ a_colon }} {{ ansible_ssh_pass }}{{ new_line }}{{ new_line }}Best Regards,{{ new_line }}Mohamed Ghaleb{{ new_line }}CloudFirst Team{{ new_line }}'
  tags:
    - e_mail

- name: Copy ThinRDP config file
  win_copy:
    src=Thinfinity.RemoteDesktop.Workstation.ini
    dest='C:\ProgramData\Cybele Software\Thinfinity\Remote Desktop Workstation\Thinfinity.RemoteDesktop.Workstation.ini'
  notify:
    - restart thinRDP
  tags:
    - cpy_thinrdp

