---

- name: restart thinRDP
  win_service:
   name: RemoteDesktopWorkstationSvc
   state: restarted

- name: mail confimration module
  local_action: mail
                host='smtp.strato.de'
                port=465
                username='info@web-wand.de'
                password='Fre!s!ng2015'
                headers=Reply-To=mohamed.ghaleb@siemens.com
                charset='UTF-8'
                from="no_reply@amazonaws.com (Mohamed Ghaleb)"
                to='{{ user_email }}'
                subject='Your CloudFirst Sandbox access details'
                body='Dear {{ user_fname }} {{ user_lname }}, {{ new_line }}{{ new_line }}Your Amazon Cloud login has been created and ready to use, below are the needed details{{ a_colon }}{{ new_line }}{{ new_line }}The url is "https{{ a_colon }}//693860272213.signin.aws.amazon.com/console"{{ new_line }}Username{{ a_colon }} {{ user_email }}{{ new_line }}Password{{ a_colon }} {{ aws_iam_pass }}{{ new_line }}{{ new_line }}If you are trying to connect to your Sandbox servers from behind a proxy, you may be facing difficulties accing them using windows Remote Desktop and/or SSH.{{ new_line }}{{ new_line }}Thus we have created for you a Jump windows computer with the needed tools (e.g. RDP, Putty) which you can access using your browser to jump into your Sandbox. You will however not be able to move files between your client PC and the Jump computer.{{ new_line }}{{ new_line }}Below are the needed details to access your Jump computer{{ a_colon }}{{ new_line }}{{ new_line }}Name Tag{{ a_colon }}{{ inventory_hostname }}{{ new_line }}URL{{ a_colon }} https{{ a_colon }}//{{ aws_route53_record }}{{ new_line }}{{ new_line }}Username{{ a_colon }} {{ windows_install_user }}{{ new_line }}Password{{ a_colon }} {{ aws_windows_pass }}{{ new_line }}{{ new_line }}Best Regards,{{ new_line }}Mohamed Ghaleb{{ new_line }}CloudFirst Team{{ new_line }}'